api_version = "2026-04"

[[extensions]]
name = "funnelx-checkout-upsell"
uid = "42a78221-416b-44aa-07ba-7ad811835d0691422ded"
type = "ui_extension"
handle = "checkout-upsell"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true
